services:
  db:
    image: postgres:16-alpine
    container_name: bot_postgres
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PGUSER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - eng-network

  web:
    build:
      context: .
      dockerfile: ./deployment/web/Dockerfile
    image: english_club_bot:latest
    container_name: english_club_bot
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./.env:/english-speaking-club-bot/.env
    env_file:
      - .env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
      - YANDEX_DICT_API_KEY=${YANDEX_DICT_API_KEY}
      - PORT=${PORT}
      - WEBHOOK_ADDRESS=${WEBHOOK_ADDRESS}
      - SEND_POLL=${SEND_POLL}
      - PGDATABASE=${PGDATABASE}
      - PGHOST=${PGHOST}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}
      - PGUSER=${PGUSER}
    networks:
      - eng-network

volumes:
  postgres_data:

networks:
  eng-network:
    driver: bridge
